server:
  port: 8084
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mariadb://localhost:3306/shop
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 2213

  jpa:
    hibernate:
      #none 으로 하는 것이 낫다.
      ddl-auto: none

    properties:
      hibernate:
        format_sql : true # sql 예쁘게 출력
        default_batch_fetch_size: 1000

    show-sql: true  # sql 출력

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.type: trace # sql binding 값 출력

file:
  upload:
    path: C:/shop/  # 윈도우파일 경로 예시 : C:/shop/

kakao:
  client:
    id: 2e466e0e1bf9da8975205bb6f4f5e869 # todo 자기 자신의 kakao.client.id 입력
    secret: URG9QeLPqt4KU1tEDesutzJ292134MUI

token:
  secret: 34fsdffa5234fdsf # todo 자신의 jwt token secret키 입력
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주

