name: project-lion-api

on:
  push:
    branches: [ develop ]
    
env:
  NAME: jujujo79 # 자신의 계정 명
  REPO: project-lion-api # 도커 허브에 만든 Repository 이름
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11    
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./project-lion-api/gradlew      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
        build-root-directory: project-lion-api
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./project-lion-api
        file: ./project-lion-api/Dockerfile
        push: true
        tags: ${{env.NAME}}/${{env.REPO}}:latest
        
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:
    
      - name: deploy run
        run: |
          sudo sh /home/ec2-user/run.sh
